### ISSUE TITLE
[Bug]: Keep getting the same "CRITICAL: Provided URL links does not point to a Notion database." error

### ISSUE THREAD

**Issue by PedroMD** [vzhd1701/csv2notion#12]
### csv2notion version

0.3.5

### What OS are you using?

MacOS

### OS Version / Linux distribution

12.5.1. Installed using brew.

### Bug description

Hi,

I can't seem to get this work as I keep getting the same `CRITICAL: Provided URL links does not point to a Notion database.` error. 
I'm sure I'm copying the proper view link using the table options (as displayed in README's example). Did something change in the API? I'm pretty sure I'm pasting the URL correctly. 

Thanks in advance!

### Log excerpt

```shell
2022-09-16 00:12:32,556 [INFO    ] Validating CSV & Notion DB schema
2022-09-16 00:12:33,307 [CRITICAL] Provided URL links does not point to a Notion database.
```

**Comment by PedroMD** [comment]
Btw, the error persists with v0.3.4

**Comment by vzhd1701** [comment]
It won't work if you don't have permission to edit the database.

**Comment by PedroMD** [comment]
I do have permission to edit the DB in question.

A sexta, 16/09/2022, 08:05, Vlad ***@***.***> escreveu:

**Comment by vzhd1701** [comment]
Sorry, I must have misread your message.

Try putting URL into quotes when you pass it to csv2notion
```
csv2notion --token TOKEN --url "URL" test.csv
```

**Comment by PedroMD** [comment]
I did try that before as well :)

**Comment by vzhd1701** [comment]
Is your link formatted like this?
`https://www.notion.so/35b837c0a61d44af8289d3929a82c292?v=87fd34e6cfd54f9a83992e5f3291474b`

**Comment by Helguera** [comment]
I found out the problem only occurs if the database is inline. It works when it is full page.
