### ISSUE TITLE
[Bug]: `csv2notion --version` is slow to execute

### ISSUE THREAD

**Issue by latenitefilms** [vzhd1701/csv2notion#6]
### csv2notion version

csv2notion 0.3.0

### What OS are you using?

MacOS

### OS Version / Linux distribution

macOS 12.4

### Bug description

Simply executing `./csv2notion --version` is slow to execute - it takes around 7sec on my machine.

Is there any reason for this? I'd expect it to be instant, given it's just returning a baked in version number?

**Comment by vzhd1701** [comment]
Do you use compiled binary or did you install it with Homebrew?

**Comment by latenitefilms** [comment]
I'm using the compiled binary.

**Comment by vzhd1701** [comment]
This is expected. The binary is compiled with pyinstaller, which means it unpacks before execution. If you want it to start faster, then I recommend installing it with Homebrew.

**Comment by latenitefilms** [comment]
Ahhh, gotcha. Thanks!
