### ISSUE TITLE
[Bug]: Default Icon argument doesn't like the ⛔ emoji

### ISSUE THREAD

**Issue by latenitefilms** [vzhd1701/csv2notion#9]
### csv2notion version

csv2notion 0.3.0

### What OS are you using?

MacOS

### OS Version / Linux distribution

macOS 12.4

### Bug description

csv2notion doesn't seem to like the ⛔ emoji?

### Log excerpt

```shell
./csv2notion --token "XXX" --default-icon "⛔"️ --verbose xxx.csv     
File not found: ⛔️
```

**Comment by vzhd1701** [comment]
Hm, strange. It works without quotes though.

**Comment by latenitefilms** [comment]
Umm, I couldn’t get it to work without quotes, however I’m triggering it through another app not directly from Terminal. Will do some more digging. Thanks for fast reply!

**Comment by vzhd1701** [comment]
From some sources the emoji comes encoded in 6 bytes, while other sources encode it in 3. Will redo emoji detection function now.

**Comment by vzhd1701** [comment]
Seems like some sources add variation selector to the emoji
https://www.emojiall.com/en/emoji/%EF%B8%8F

Should be fixed now. Check out the new version.

**Comment by latenitefilms** [comment]
Fixed - thanks heaps @vzhd1701!
